// src/config/sidebarModules.js
import {
  FaStore,
  FaUsers,
  FaBoxes,
  FaShoppingCart,
  FaLayerGroup,
  FaReceipt,
  FaListAlt,
} from "react-icons/fa";

export const SIDEBAR_MODULES = [
  { id: "shops", label: "Shops", icon: FaStore },
  { id: "users", label: "Employees", icon: FaUsers },
  { id: "product", label: "Products", icon: FaBoxes },
  { id: "purchases", label: "Purchases", icon: FaShoppingCart },
  { id: "inventory", label: "Inventory", icon: FaLayerGroup },
  { id: "low-stock-report", label: "Low Stock Report", icon: FaLayerGroup },
  { id: "stock-transfer", label: "Stock Transfer", icon: FaLayerGroup },
  { id: "orders", label: "Orders", icon: FaLayerGroup },
  { id: "customer", label: "Customer", icon: FaUsers },
  { id: "customer-ledger", label: "Customer Ledger", icon: FaUsers },
  { id: "vendors", label: "Vendors", icon: FaUsers },
  { id: "product-packs", label: "Production History", icon: FaBoxes },
  { id: "admin-settings", label: "Financial Year", icon: FaLayerGroup },
  { id: "permissions", label: "Permission Management", icon: FaUsers },
  { id: "sales-create", label: "Sales Form", icon: FaReceipt },
  { id: "sales-list", label: "Sales List", icon: FaListAlt },
  { id: "ledger-product", label: "Product Ledger", icon: FaListAlt },
  { id: "ledger-sales", label: "Sales Ledger", icon: FaListAlt },
  { id: "ledger-purchase", label: "Purchase Ledger", icon: FaListAlt },
  { id: "ledger-customer", label: "Customer Analytics", icon: FaListAlt },
  { id: "ledger-stock-transfer", label: "Stock Transfer Ledger", icon: FaListAlt },
  { id: "android", label: "Android", icon: FaStore },
];
